# Generated by Django 2.2.7 on 2019-11-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momo_devc_app', '0002_auto_20191130_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='embedding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
